### ISSUE TITLE
Translation of "Level Help"

### ISSUE THREAD

**Issue by Men-cotton** [hsjoihs/nandgame-translate-ja#6]
左のボタンでは「ステージのヘルプ」となっています。

![Screenshot 2024-09-08 at 11-24-59 NandGame - Build a computer from scratch](https://github.com/user-attachments/assets/a8541c70-1c06-4507-bcb1-52f92a929081)

一方、イントロダクションでは、「ステージのヒント」となっています。

![Screenshot 2024-09-08 at 11-25-28 NandGame - Build a computer from scratch](https://github.com/user-attachments/assets/e3260489-14ca-4ec6-9cab-a44cfecd1577)

**Comment by hsjoihs** [comment]
0d2ef83 で対応しました。更新した JSON を原作者に送付したので、デプロイされるまでお待ちください。
