### ISSUE TITLE
ステージ「アセンブリプログラム」などで、「show Assembler Help」で表示できる「Assembler quick reference」が翻訳されていない

### ISSUE THREAD

**Issue by yamina-Tjatmg-Gui-Creater** [hsjoihs/nandgame-translate-ja#7]
どうやら選択コピーすることもできなく、翻訳ソフトを使うことができないそうです。

**Comment by hsjoihs** [comment]
38839a240a0b33780db33dff38ac7bc2c78f70ae で対応しました。更新した JSON を原作者に送付したので、デプロイされるまでお待ちください。

**Comment by hsjoihs** [comment]
無事デプロイされました。

<img width="945" alt="nandgame" src="https://github.com/user-attachments/assets/539ce7bd-8c23-43d4-ba7a-b32d9718544f">
